//AUTOGENERATED FILE FROM png2asset
// Conversion args: \Z94SNQ_splashscreen.png -map -keep_palette_order -noflip

#ifndef METASPRITE_Z94SNQ_splashscreen_H
#define METASPRITE_Z94SNQ_splashscreen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Z94SNQ_splashscreen_TILE_ORIGIN 0
#define Z94SNQ_splashscreen_TILE_W 8
#define Z94SNQ_splashscreen_TILE_H 8
#define Z94SNQ_splashscreen_WIDTH 160
#define Z94SNQ_splashscreen_HEIGHT 144
#define Z94SNQ_splashscreen_TILE_COUNT 37
#define Z94SNQ_splashscreen_PALETTE_COUNT 1
#define Z94SNQ_splashscreen_COLORS_PER_PALETTE 4
#define Z94SNQ_splashscreen_TOTAL_COLORS 4
#define Z94SNQ_splashscreen_MAP_ATTRIBUTES 0
extern const unsigned char Z94SNQ_splashscreen_map[360];
#define Z94SNQ_splashscreen_map_attributes Z94SNQ_splashscreen_map

BANKREF_EXTERN(Z94SNQ_splashscreen)

extern const palette_color_t Z94SNQ_splashscreen_palettes[4];
extern const uint8_t Z94SNQ_splashscreen_tiles[592];

#endif
